version: '3'

services:
  python_app:
    build: .
    working_dir: /django_mac_site/$PROJECTNAME/
    command: python3 manage.py runserver 0.0.0.0:5090
    #gunicorn -b 0.0.0.0:5000 $PROJECTNAME.wsgi
    volumes:
      - .:/django_mac_site
    env_file:
      - .env
    ports:
      - "5090:5090"
    depends_on:
      - db

  #proxy:
    #build: ./nginx
    #ports:
    #  - "5000:80"

  db:
    build: ./postgres
    #volumes:
    #  - ./postgres/postgres_data:/var/lib/postgresql/data/
